theme: jekyll-theme-minimal
title: grdfConnect_- Jeedom plugin for GRDF Gazpar
description: Jeedom plugin to retrieve gaz consumption from GRDF website
show_downloads: true
logo: /assets/images/logo.png